name: Tests
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          source ./test.sh
          for DAY in $(ls -d [0-9][0-9]); do
            run_tests_for_day ${DAY}

            if [[ $? -ne 0 ]]; then
              exit 1
            fi
          done
